site_name: eBPF Docs

repo_url: https://github.com/isovalent/ebpf-docs
edit_uri: blob/master/docs/

theme:
  name: material
  logo: assets/image/logo.png
  favicon: assets/image/favicon-32x32.png
  features:
    - navigation.indexes
    - navigation.top
    - content.action.view
    - content.action.edit
  font:
    text: Inter
    code: Inter
  palette:
    scheme: slate
    primary: yellow
    accent: amber

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

  custom_dir: overwrites

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.inlinehilite
  - abbr
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang: en
      separator: '[\s\-\_\.]+'
  - literate-nav:
      nav_file: SUMMARY.md
      tab_length: 2
  - git-revision-date-localized:
      enabled: !ENV [PROD, false]
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [PROD, false]
      token: !ENV ["GH_TOKEN"]
      repository: isovalent/ebpf-docs
      branch: master
  - social:
      cards_layout_options:
        logo: docs/assets/image/logo.png

extra_css:
  - stylesheets/extra.css
